language: python
python:
  - "2.7"
install: pip install -r requirements/dev.txt
script: coverage run --source=electionleaflets manage.py test
script: coverage run --source=electionleaflets manage.py harvest
after_success:
  - coveralls
notifications:
  slack: democracyclub:xPS8z1f2rT5iv25aeXtF6Ikl
